use std::env;
use std::path::PathBuf;
use std::process::ExitCode;

use mage_build::bundle::{Bundle, Config, RenderContext, Template};
use mage_build::error::Result;
use mage_build::module::{Dependency, Module};
use mage_build::toolchain::Toolchain;

fn main() -> ExitCode {
    let args: Vec<String> = env::args().skip(1).collect();

    match args.first().map(|s| s.as_str()) {
        Some("bootstrap") => run(bootstrap),
        Some("brew") => run(brew),
        Some("help") | None => {
            print_help();
            ExitCode::SUCCESS
        }
        Some(cmd) => {
            eprintln!("error: unknown command '{cmd}'");
            eprintln!();
            print_help();
            ExitCode::FAILURE
        }
    }
}

fn run(f: fn() -> Result<()>) -> ExitCode {
    match f() {
        Ok(()) => ExitCode::SUCCESS,
        Err(e) => {
            eprintln!("error: {e}");
            ExitCode::FAILURE
        }
    }
}

fn print_help() {
    eprintln!("usage: cargo xtask <command>");
    eprintln!();
    eprintln!("commands:");
    eprintln!("  bootstrap   Build generation-zero mage binary from workspace sources");
    eprintln!("  brew        Generate Homebrew formula for mage");
    eprintln!("  help        Show this help");
}

// ---------------------------------------------------------------------------
// Paths
// ---------------------------------------------------------------------------

/// Workspace root — xtask binary lives in `<root>/xtask/`, so go up one.
fn workspace_root() -> PathBuf {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR")
        .map(PathBuf::from)
        .unwrap_or_else(|_| env::current_dir().unwrap());

    // If running via `cargo xtask`, CARGO_MANIFEST_DIR points to xtask/.
    // Walk up until we find the workspace Cargo.toml.
    let mut dir = manifest_dir.as_path();
    loop {
        let candidate = dir.join("Cargo.toml");
        if candidate.exists() {
            let content = std::fs::read_to_string(&candidate).unwrap_or_default();
            if content.contains("[workspace]") {
                return dir.to_path_buf();
            }
        }
        dir = match dir.parent() {
            Some(p) => p,
            None => {
                // Fallback — assume cwd.
                return env::current_dir().unwrap();
            }
        };
    }
}

// ---------------------------------------------------------------------------
// Bootstrap
// ---------------------------------------------------------------------------

/// Template that generates a minimal mage host binary.
///
/// This is generation zero — the first binary bootstrapped from workspace
/// sources. It wires up the agent loop, registers discovered extensions,
/// and starts an interactive or single-prompt session.
struct BootstrapTemplate;

impl Template for BootstrapTemplate {
    fn render_main(&self, ctx: &RenderContext) -> Result<String> {
        let mut mod_decls = String::new();
        let mut init_calls = String::new();

        for m in ctx.modules {
            let mod_name = m.name.replace('-', "_");

            // Only include modules that have an init function.
            if m.init.is_some() {
                mod_decls.push_str(&format!(
                    "#[path = \"modules/{}.rs\"]\nmod {mod_name};\n",
                    m.name
                ));
                init_calls.push_str(&format!("    {mod_name}::init(&mut registry);\n"));
            }
        }

        Ok(format!(
            r#"//! Generated by `cargo xtask bootstrap` — do not edit.
use mage_core::extension::Registry;

{mod_decls}
fn main() {{
    let rt = tokio::runtime::Builder::new_current_thread()
        .enable_all()
        .build()
        .expect("failed to build tokio runtime");

    rt.block_on(async {{
        let mut tools = Vec::new();
        let mut providers = Vec::new();
        let mut registry = Registry {{
            tools: &mut tools,
            providers: &mut providers,
        }};
{init_calls}
        eprintln!("mage: bootstrap binary ready");
        eprintln!("mage: {{}} tool(s) registered", tools.len());
        eprintln!("mage: {{}} provider(s) registered", providers.len());
    }});
}}
"#
        ))
    }

    fn render_dependencies(&self, _ctx: &RenderContext) -> Result<Vec<Dependency>> {
        // The bootstrap binary needs mage-core and tokio at minimum.
        // These come from core_crates — no extra deps needed from the template.
        Ok(vec![])
    }
}

fn bootstrap() -> Result<()> {
    let root = workspace_root();
    eprintln!("workspace root: {}", root.display());

    // Scan extensions/ for any .rs modules.
    let ext_dir = root.join("extensions").join("tools-coding");
    let mut modules = Vec::new();

    if ext_dir.is_dir() {
        for entry in std::fs::read_dir(&ext_dir)? {
            let entry = entry?;
            let path = entry.path();
            if path.extension().is_some_and(|e| e == "rs") {
                let name = path.file_stem().unwrap_or_default().to_string_lossy();
                match Module::parse_file(&path, &name) {
                    Ok(m) => {
                        eprintln!("  found extension: {} ({})", m.name, path.display());
                        modules.push(m);
                    }
                    Err(e) => {
                        eprintln!("  warning: failed to parse {}: {e}", path.display());
                    }
                }
            }
        }
    }

    if modules.is_empty() {
        eprintln!("  no extensions found (extensions/tools-coding/ is empty)");
    }

    // Build the bundle with core crates from the workspace.
    let config = Config {
        approot: root.join("target/mage-bootstrap"),
        ..Config::default()
    };

    let mut bundle = Bundle::new("mage-bootstrap")
        .with_config(config)
        .add_core_crate(root.join("pkg/sdk"))
        .add_core_crate(root.join("pkg/core"))
        .add_core_crate(root.join("pkg/llm"))
        .add_core_crate(root.join("pkg/refstr"))
        .add_core_crate(root.join("pkg/tui"))
        .add_core_crate(root.join("pkg/build"))
        .add_core_crate(root.join("providers/anthropic"))
        .with_template(BootstrapTemplate);

    for m in modules {
        bundle = bundle.add_module(m);
    }

    // Resolve toolchain.
    let toolchain = Toolchain::resolve_system()?;
    eprintln!("toolchain: {} / {}", toolchain.rustc_path.display(), toolchain.cargo_path.display());
    bundle = bundle.with_toolchain(toolchain);

    // Generate workspace.
    eprintln!("generating workspace...");
    bundle.generate()?;

    let hash = bundle.content_hash()?;
    eprintln!("content hash: {}", &hash[..12]);

    // Compile.
    eprintln!("compiling...");
    let result = bundle.compile()?;

    if !result.warnings.is_empty() {
        eprintln!("{} warning(s)", result.warnings.len());
    }

    if result.success {
        if let Some(ref bin) = result.executable_path {
            eprintln!("success: {}", bin.display());
        } else {
            eprintln!("success (no binary path returned)");
        }
    } else {
        eprintln!("compilation failed:");
        eprintln!("{}", result.format_errors());
        return Err(mage_build::error::Error::Bundle("bootstrap compilation failed".into()));
    }

    Ok(())
}

// ---------------------------------------------------------------------------
// Brew
// ---------------------------------------------------------------------------

fn brew() -> Result<()> {
    let root = workspace_root();
    let formula_path = root.join("dist").join("mage.rb");

    std::fs::create_dir_all(formula_path.parent().unwrap())?;

    let formula = r##"class Mage < Formula
  desc "Self-replicating AI coding agent"
  homepage "https://github.com/semtexzv/mage"
  license "MIT"

  # TODO: fill in actual release URL and SHA once published
  # url "https://github.com/semtexzv/mage/archive/refs/tags/v0.1.0.tar.gz"
  # sha256 "TODO"

  depends_on "rust" => :build

  def install
    system "cargo", "install", "--path", "xtask", "--root", buildpath/"xtask-bin"
    system buildpath/"xtask-bin/bin/xtask", "bootstrap"

    # The bootstrap process puts the binary in .mage/bin/
    mage_bin = Dir[buildpath/".mage/bin/mage-*"].first
    if mage_bin
      bin.install mage_bin => "mage"
    else
      # Fallback: build directly
      system "cargo", "build", "--release", "-p", "xtask"
      odie "Bootstrap failed — no binary produced"
    end
  end

  test do
    assert_match "mage", shell_output("#{bin}/mage --version 2>&1", 1)
  end
end
"##;

    std::fs::write(&formula_path, formula)?;
    eprintln!("wrote {}", formula_path.display());
    Ok(())
}
