use std::env;
use std::path::PathBuf;
use std::process::ExitCode;

use mage_build::bundle::{Bundle, Config, RenderContext, Template};
use mage_build::error::Result;
use mage_build::module::{Dependency, Module};
use mage_build::toolchain::Toolchain;

fn main() -> ExitCode {
    let args: Vec<String> = env::args().skip(1).collect();

    match args.first().map(|s| s.as_str()) {
        Some("bootstrap") => run(bootstrap),
        Some("brew") => run(brew),
        Some("help") | None => {
            print_help();
            ExitCode::SUCCESS
        }
        Some(cmd) => {
            eprintln!("error: unknown command '{cmd}'");
            eprintln!();
            print_help();
            ExitCode::FAILURE
        }
    }
}

fn run(f: fn() -> Result<()>) -> ExitCode {
    match f() {
        Ok(()) => ExitCode::SUCCESS,
        Err(e) => {
            eprintln!("error: {e}");
            ExitCode::FAILURE
        }
    }
}

fn print_help() {
    eprintln!("usage: cargo xtask <command>");
    eprintln!();
    eprintln!("commands:");
    eprintln!("  bootstrap   Build generation-zero mage binary from workspace sources");
    eprintln!("  brew        Generate Homebrew formula for mage");
    eprintln!("  help        Show this help");
}

// ---------------------------------------------------------------------------
// Paths
// ---------------------------------------------------------------------------

/// Workspace root — xtask binary lives in `<root>/xtask/`, so go up one.
fn workspace_root() -> PathBuf {
    let manifest_dir = env::var("CARGO_MANIFEST_DIR")
        .map(PathBuf::from)
        .unwrap_or_else(|_| env::current_dir().unwrap());

    // If running via `cargo xtask`, CARGO_MANIFEST_DIR points to xtask/.
    // Walk up until we find the workspace Cargo.toml.
    let mut dir = manifest_dir.as_path();
    loop {
        let candidate = dir.join("Cargo.toml");
        if candidate.exists() {
            let content = std::fs::read_to_string(&candidate).unwrap_or_default();
            if content.contains("[workspace]") {
                return dir.to_path_buf();
            }
        }
        dir = match dir.parent() {
            Some(p) => p,
            None => {
                // Fallback — assume cwd.
                return env::current_dir().unwrap();
            }
        };
    }
}

// ---------------------------------------------------------------------------
// Bootstrap
// ---------------------------------------------------------------------------

/// Template that generates the mage binary.
///
/// This is generation zero — the first binary bootstrapped from workspace
/// sources. It wires up extensions, the agent loop, the application layer,
/// and the TUI event loop.
struct BootstrapTemplate;
impl Template for BootstrapTemplate {
    fn render_main(&self, ctx: &RenderContext) -> Result<String> {
        let mut mod_decls = String::new();
        let mut ext_calls = String::new();
        for m in ctx.modules {
            let mod_name = m.name.replace('-', "_");
            // Only include modules that have an init function.
            if m.init.is_some() {
                mod_decls.push_str(&format!(
                    "#[path = \"modules/{}.rs\"]\nmod {mod_name};\n",
                    m.name
                ));
                ext_calls.push_str(&format!("        extensions.extend({mod_name}::extensions());\n"));
            }
        }
        let mut out = String::new();
        out.push_str("//! Generated by `cargo xtask bootstrap` \u{2014} do not edit.\n\n");
        out.push_str("use mage::prelude::*;\n");
        out.push_str("use mage::llm;\nuse mage::llm::Provider as _;\n\n");
        out.push_str(&mod_decls);
        out.push_str("\n");
        out.push_str("fn main() {\n");
        out.push_str("    let rt = tokio::runtime::Builder::new_current_thread()\n");
        out.push_str("        .enable_all()\n");
        out.push_str("        .build()\n");
        out.push_str("        .expect(\"failed to build tokio runtime\");\n\n");
        out.push_str("    let local = tokio::task::LocalSet::new();\n");
        out.push_str("    local.block_on(&rt, async {\n");
        out.push_str("        // Collect extensions from discovered modules.\n");
        out.push_str("        let mut extensions: Vec<Box<dyn Extension>> = Vec::new();\n");
        out.push_str(&ext_calls);
        // Load persisted credentials from disk.
        out.push_str("        let cred_path = mage::app::credentials::default_path();\n");
        out.push_str("        let oauth_slot: std::rc::Rc<std::cell::RefCell<Option<anthropic::oauth::OAuthCredentials>>> =\n");
        out.push_str("            std::rc::Rc::new(std::cell::RefCell::new(None));\n\n");
        out.push_str("        if let Some(ref path) = cred_path {\n");
        out.push_str("            let store = mage::app::credentials::load(path);\n");
        out.push_str("            if let Some(mage::app::credentials::Credential::OAuth {\n");
        out.push_str("                refresh_token, access_token, expires_at_ms\n");
        out.push_str("            }) = store.get(\"anthropic\") {\n");
        out.push_str("                *oauth_slot.borrow_mut() = Some(anthropic::oauth::OAuthCredentials {\n");
        out.push_str("                    refresh_token: refresh_token.clone(),\n");
        out.push_str("                    access_token: access_token.clone(),\n");
        out.push_str("                    expires_at_ms: *expires_at_ms,\n");
        out.push_str("                });\n");
        out.push_str("            }\n");
        out.push_str("        }\n\n");

        // Anthropic provider — env vars override stored credentials.
        out.push_str("        // Anthropic provider — env vars override stored credentials.\n");
        out.push_str("        let mut provider = anthropic::AnthropicProvider::new()\n");
        out.push_str("            .with_oauth_shared(oauth_slot.clone());\n");
        out.push_str("        if let Ok(refresh) = std::env::var(\"ANTHROPIC_OAUTH_REFRESH_TOKEN\") {\n");
        out.push_str("            // Env var OAuth overrides stored credentials.\n");
        out.push_str("            let access = std::env::var(\"ANTHROPIC_OAUTH_ACCESS_TOKEN\")\n");
        out.push_str("                .unwrap_or_default();\n");
        out.push_str("            *oauth_slot.borrow_mut() = Some(anthropic::oauth::OAuthCredentials {\n");
        out.push_str("                refresh_token: refresh,\n");
        out.push_str("                access_token: access,\n");
        out.push_str("                expires_at_ms: 0, // force immediate refresh\n");
        out.push_str("            });\n");
        out.push_str("        } else if let Ok(api_key) = std::env::var(\"ANTHROPIC_API_KEY\") {\n");
        out.push_str("            provider = provider.with_api_key(&api_key);\n");
        out.push_str("        }\n\n");

        // Build model and agent.
        out.push_str("        // Build agent.\n");
        out.push_str("        let model = llm::types::Model {\n");
        out.push_str("            id: \"claude-sonnet-4-20250514\".into(),\n");
        out.push_str("            name: \"Claude Sonnet 4\".into(),\n");
        out.push_str("            api: \"anthropic\".into(),\n");
        out.push_str("            provider: \"anthropic\".into(),\n");
        out.push_str("            base_url: \"https://api.anthropic.com\".into(),\n");
        out.push_str("            reasoning: false,\n");
        out.push_str("            input: vec![],\n");
        out.push_str("            cost: llm::types::ModelCost::default(),\n");
        out.push_str("            context_window: 200_000,\n");
        out.push_str("            max_out: 16_384,\n");
        out.push_str("            headers: None,\n");
        out.push_str("        };\n");
        out.push_str("        let model_name = model.name.to_string();\n\n");
        out.push_str("        let provider = std::rc::Rc::new(provider);\n");
        out.push_str("        let authenticator: std::rc::Rc<dyn mage::llm::Authenticator> = provider.clone();\n\n");
        out.push_str("        let providers: Vec<(refstr::Str, std::rc::Rc<dyn mage::llm::Provider>)> = vec![\n");
        out.push_str("            (\"anthropic\".into(), provider.clone() as std::rc::Rc<dyn mage::llm::Provider>),\n");
        out.push_str("        ];\n");
        out.push_str("        let (mut agent_loop, event_rx) = mage::agent_loop::AgentLoop::new(\n");
        out.push_str("            \"You are a helpful coding assistant.\",\n");
        out.push_str("            model,\n");
        out.push_str("            mage::llm::StreamOptions::default(),\n");
        out.push_str("            providers,\n");
        out.push_str("            extensions,\n");
        out.push_str("        );\n");
        out.push_str("        let handle = mage::session::spawn(agent_loop);\n");
        out.push_str("        let app = App::new(handle);\n\n");
        // Save callback for after login.
        out.push_str("        // Credential save callback — fires after login success.\n");
        out.push_str("        let save_slot = oauth_slot.clone();\n");
        out.push_str("        let save_path = cred_path.clone();\n");
        out.push_str("        let on_cred_save: Option<std::rc::Rc<dyn Fn()>> = save_path.map(|path| {\n");
        out.push_str("            std::rc::Rc::new(move || {\n");
        out.push_str("                if let Some(ref creds) = *save_slot.borrow() {\n");
        out.push_str("                    let _ = mage::app::credentials::save_oauth(\n");
        out.push_str("                        &path, \"anthropic\",\n");
        out.push_str("                        &creds.refresh_token, &creds.access_token, creds.expires_at_ms,\n");
        out.push_str("                    );\n");
        out.push_str("                }\n");
        out.push_str("            }) as std::rc::Rc<dyn Fn()>\n");
        out.push_str("        });\n\n");
        out.push_str("        let available_models = provider.models();\n");
        out.push_str("        mage::app::tui::run(app, event_rx, Some(authenticator), on_cred_save, available_models, model_name).await;\n");
        out.push_str("    });\n");
        out.push_str("}\n");
        Ok(out)
    }
    fn render_dependencies(&self, _ctx: &RenderContext) -> Result<Vec<Dependency>> {
        // Core crates (mage, mage-core, mage-llm, mage-tui, mage-build, mage-anthropic,
        // refstr) are already injected via add_core_crate. Template only needs to
        // add extra non-core deps the generated main.rs uses directly.
        Ok(vec![])
    }
}

fn bootstrap() -> Result<()> {
    let root = workspace_root();
    eprintln!("workspace root: {}", root.display());

    // Scan extensions/ for any .rs modules.
    let ext_dir = root.join("extensions").join("tools-coding");
    let mut modules = Vec::new();

    if ext_dir.is_dir() {
        for entry in std::fs::read_dir(&ext_dir)? {
            let entry = entry?;
            let path = entry.path();
            if path.extension().is_some_and(|e| e == "rs") {
                let name = path.file_stem().unwrap_or_default().to_string_lossy();
                match Module::parse_file(&path, &name) {
                    Ok(m) => {
                        eprintln!("  found extension: {} ({})", m.name, path.display());
                        modules.push(m);
                    }
                    Err(e) => {
                        eprintln!("  warning: failed to parse {}: {e}", path.display());
                    }
                }
            }
        }
    }

    if modules.is_empty() {
        eprintln!("  no extensions found (extensions/tools-coding/ is empty)");
    }

    // Build the bundle with core crates from the workspace.
    let config = Config {
        approot: root.join("target/mage-bootstrap"),
        ..Config::default()
    };

    let mut bundle = Bundle::new("mage-bootstrap")
        .with_config(config)
        .add_core_crate(root.join("pkg/sdk"))
        .add_core_crate(root.join("pkg/core"))
        .add_core_crate(root.join("pkg/llm"))
        .add_core_crate(root.join("pkg/refstr"))
        .add_core_crate(root.join("pkg/tui"))
        .add_core_crate(root.join("pkg/build"))
        .add_core_crate(root.join("pkg/app"))
        .add_core_crate(root.join("providers/anthropic"))
        .with_template(BootstrapTemplate);

    for m in modules {
        bundle = bundle.add_module(m);
    }

    // Resolve toolchain.
    let toolchain = Toolchain::resolve_system()?;
    eprintln!("toolchain: {} / {}", toolchain.rustc_path.display(), toolchain.cargo_path.display());
    bundle = bundle.with_toolchain(toolchain);

    // Generate workspace.
    eprintln!("generating workspace...");
    bundle.generate()?;

    let hash = bundle.content_hash()?;
    eprintln!("content hash: {}", &hash[..12]);

    // Compile.
    eprintln!("compiling...");
    let result = bundle.compile()?;

    if !result.warnings.is_empty() {
        eprintln!("{} warning(s)", result.warnings.len());
    }

    if result.success {
        if let Some(ref bin) = result.executable_path {
            eprintln!("success: {}", bin.display());
        } else {
            eprintln!("success (no binary path returned)");
        }
    } else {
        eprintln!("compilation failed:");
        eprintln!("{}", result.format_errors());
        return Err(mage_build::error::Error::Bundle("bootstrap compilation failed".into()));
    }

    Ok(())
}

// ---------------------------------------------------------------------------
// Brew
// ---------------------------------------------------------------------------

fn brew() -> Result<()> {
    let root = workspace_root();
    let formula_path = root.join("dist").join("mage.rb");

    std::fs::create_dir_all(formula_path.parent().unwrap())?;

    let formula = r##"class Mage < Formula
  desc "Self-replicating AI coding agent"
  homepage "https://github.com/semtexzv/mage"
  license "MIT"

  # TODO: fill in actual release URL and SHA once published
  # url "https://github.com/semtexzv/mage/archive/refs/tags/v0.1.0.tar.gz"
  # sha256 "TODO"

  depends_on "rust" => :build

  def install
    system "cargo", "install", "--path", "xtask", "--root", buildpath/"xtask-bin"
    system buildpath/"xtask-bin/bin/xtask", "bootstrap"

    # The bootstrap process puts the binary in .mage/bin/
    mage_bin = Dir[buildpath/".mage/bin/mage-*"].first
    if mage_bin
      bin.install mage_bin => "mage"
    else
      # Fallback: build directly
      system "cargo", "build", "--release", "-p", "xtask"
      odie "Bootstrap failed — no binary produced"
    end
  end

  test do
    assert_match "mage", shell_output("#{bin}/mage --version 2>&1", 1)
  end
end
"##;

    std::fs::write(&formula_path, formula)?;
    eprintln!("wrote {}", formula_path.display());
    Ok(())
}
